name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install
    
    - name: Set up Docker Buildx      
      uses: crazy-max/ghaction-docker-buildx@v1      
      with:        
        version: latest    
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}        
    
    - name: Build the Docker image
      run: docker buildx build . --file Dockerfile --tag dkaukov/tci-mqtt-gateway:latest --platform linux/arm/v7 --build-arg ARCH=arm32v7
    - name: Push the Docker image
      run: docker buildx push dkaukov/tci-mqtt-gateway:latest
