name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install
    
    - name: Set up Docker Buildx      
      uses: crazy-max/ghaction-docker-buildx@v1      
      with:        
        version: latest    
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}        
    
    - name: Build the Docker image (ArmV7)
      run: docker buildx build . --file Dockerfile --tag dkaukov/tci-mqtt-gateway:latest --tag dkaukov/tci-mqtt-gateway:$(date +%s) --platform linux/arm/v6,linux/arm64/v8,linux/amd64 --output type=image,push=true
#    - name: Build the Docker image (amd64)
#      run: docker build . --file Dockerfile --tag dkaukov/tci-mqtt-gateway:latest     
#    - name: Push the Docker image
#      run: docker push dkaukov/tci-mqtt-gateway:latest
